// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbR9u7-ctFak-VUFkendv9bBBNufYeFm0',
    appId: '1:420464524498:web:025162e38f9a3b1846810b',
    messagingSenderId: '420464524498',
    projectId: 'meal-planning-fe26a',
    authDomain: 'meal-planning-fe26a.firebaseapp.com',
    storageBucket: 'meal-planning-fe26a.appspot.com',
    measurementId: 'G-GNVH31R5D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOoTBdaVDys50Cj6blgV-WtebGfd548wk',
    appId: '1:420464524498:android:2ffbefdf10c8ee0a46810b',
    messagingSenderId: '420464524498',
    projectId: 'meal-planning-fe26a',
    storageBucket: 'meal-planning-fe26a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMxfeIGT5IK9CJxB4csutNfO_wz8SusVc',
    appId: '1:420464524498:ios:35bb5b2bdaad796146810b',
    messagingSenderId: '420464524498',
    projectId: 'meal-planning-fe26a',
    storageBucket: 'meal-planning-fe26a.appspot.com',
    iosClientId: '420464524498-9r24tm2ku28degttnvclkmqljk2ui0to.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealPlanning',
  );
}
